# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/771/bin/cmake

# The command to remove a file.
RM = /snap/cmake/771/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/MyProjects/MrBoboWeb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/MyProjects/MrBoboWeb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/771/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/745/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/MyProjects/MrBoboWeb/CMakeFiles /home/pi/MyProjects/MrBoboWeb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/MyProjects/MrBoboWeb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BasicChatCmake

# Build rule for target.
BasicChatCmake: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BasicChatCmake
.PHONY : BasicChatCmake

# fast build rule for target.
BasicChatCmake/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/build
.PHONY : BasicChatCmake/fast

BasiChatCmake.o: BasiChatCmake.cpp.o

.PHONY : BasiChatCmake.o

# target to build an object file
BasiChatCmake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/BasiChatCmake.cpp.o
.PHONY : BasiChatCmake.cpp.o

BasiChatCmake.i: BasiChatCmake.cpp.i

.PHONY : BasiChatCmake.i

# target to preprocess a source file
BasiChatCmake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/BasiChatCmake.cpp.i
.PHONY : BasiChatCmake.cpp.i

BasiChatCmake.s: BasiChatCmake.cpp.s

.PHONY : BasiChatCmake.s

# target to generate assembly for a file
BasiChatCmake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/BasiChatCmake.cpp.s
.PHONY : BasiChatCmake.cpp.s

BasicChat/BasicChatMain.o: BasicChat/BasicChatMain.cpp.o

.PHONY : BasicChat/BasicChatMain.o

# target to build an object file
BasicChat/BasicChatMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/BasicChat/BasicChatMain.cpp.o
.PHONY : BasicChat/BasicChatMain.cpp.o

BasicChat/BasicChatMain.i: BasicChat/BasicChatMain.cpp.i

.PHONY : BasicChat/BasicChatMain.i

# target to preprocess a source file
BasicChat/BasicChatMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/BasicChat/BasicChatMain.cpp.i
.PHONY : BasicChat/BasicChatMain.cpp.i

BasicChat/BasicChatMain.s: BasicChat/BasicChatMain.cpp.s

.PHONY : BasicChat/BasicChatMain.s

# target to generate assembly for a file
BasicChat/BasicChatMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/BasicChat/BasicChatMain.cpp.s
.PHONY : BasicChat/BasicChatMain.cpp.s

MBErrorHandling.o: MBErrorHandling.cpp.o

.PHONY : MBErrorHandling.o

# target to build an object file
MBErrorHandling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MBErrorHandling.cpp.o
.PHONY : MBErrorHandling.cpp.o

MBErrorHandling.i: MBErrorHandling.cpp.i

.PHONY : MBErrorHandling.i

# target to preprocess a source file
MBErrorHandling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MBErrorHandling.cpp.i
.PHONY : MBErrorHandling.cpp.i

MBErrorHandling.s: MBErrorHandling.cpp.s

.PHONY : MBErrorHandling.s

# target to generate assembly for a file
MBErrorHandling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MBErrorHandling.cpp.s
.PHONY : MBErrorHandling.cpp.s

MrBoboChatt/MBCProtocols.o: MrBoboChatt/MBCProtocols.cpp.o

.PHONY : MrBoboChatt/MBCProtocols.o

# target to build an object file
MrBoboChatt/MBCProtocols.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrBoboChatt/MBCProtocols.cpp.o
.PHONY : MrBoboChatt/MBCProtocols.cpp.o

MrBoboChatt/MBCProtocols.i: MrBoboChatt/MBCProtocols.cpp.i

.PHONY : MrBoboChatt/MBCProtocols.i

# target to preprocess a source file
MrBoboChatt/MBCProtocols.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrBoboChatt/MBCProtocols.cpp.i
.PHONY : MrBoboChatt/MBCProtocols.cpp.i

MrBoboChatt/MBCProtocols.s: MrBoboChatt/MBCProtocols.cpp.s

.PHONY : MrBoboChatt/MBCProtocols.s

# target to generate assembly for a file
MrBoboChatt/MBCProtocols.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrBoboChatt/MBCProtocols.cpp.s
.PHONY : MrBoboChatt/MBCProtocols.cpp.s

MrBoboChatt/MBChatConnection.o: MrBoboChatt/MBChatConnection.cpp.o

.PHONY : MrBoboChatt/MBChatConnection.o

# target to build an object file
MrBoboChatt/MBChatConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrBoboChatt/MBChatConnection.cpp.o
.PHONY : MrBoboChatt/MBChatConnection.cpp.o

MrBoboChatt/MBChatConnection.i: MrBoboChatt/MBChatConnection.cpp.i

.PHONY : MrBoboChatt/MBChatConnection.i

# target to preprocess a source file
MrBoboChatt/MBChatConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrBoboChatt/MBChatConnection.cpp.i
.PHONY : MrBoboChatt/MBChatConnection.cpp.i

MrBoboChatt/MBChatConnection.s: MrBoboChatt/MBChatConnection.cpp.s

.PHONY : MrBoboChatt/MBChatConnection.s

# target to generate assembly for a file
MrBoboChatt/MBChatConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrBoboChatt/MBChatConnection.cpp.s
.PHONY : MrBoboChatt/MBChatConnection.cpp.s

MrBoboChatt/MrBoboChatt.o: MrBoboChatt/MrBoboChatt.cpp.o

.PHONY : MrBoboChatt/MrBoboChatt.o

# target to build an object file
MrBoboChatt/MrBoboChatt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrBoboChatt/MrBoboChatt.cpp.o
.PHONY : MrBoboChatt/MrBoboChatt.cpp.o

MrBoboChatt/MrBoboChatt.i: MrBoboChatt/MrBoboChatt.cpp.i

.PHONY : MrBoboChatt/MrBoboChatt.i

# target to preprocess a source file
MrBoboChatt/MrBoboChatt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrBoboChatt/MrBoboChatt.cpp.i
.PHONY : MrBoboChatt/MrBoboChatt.cpp.i

MrBoboChatt/MrBoboChatt.s: MrBoboChatt/MrBoboChatt.cpp.s

.PHONY : MrBoboChatt/MrBoboChatt.s

# target to generate assembly for a file
MrBoboChatt/MrBoboChatt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrBoboChatt/MrBoboChatt.cpp.s
.PHONY : MrBoboChatt/MrBoboChatt.cpp.s

MrPostOGet/TLSHandler.o: MrPostOGet/TLSHandler.cpp.o

.PHONY : MrPostOGet/TLSHandler.o

# target to build an object file
MrPostOGet/TLSHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrPostOGet/TLSHandler.cpp.o
.PHONY : MrPostOGet/TLSHandler.cpp.o

MrPostOGet/TLSHandler.i: MrPostOGet/TLSHandler.cpp.i

.PHONY : MrPostOGet/TLSHandler.i

# target to preprocess a source file
MrPostOGet/TLSHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrPostOGet/TLSHandler.cpp.i
.PHONY : MrPostOGet/TLSHandler.cpp.i

MrPostOGet/TLSHandler.s: MrPostOGet/TLSHandler.cpp.s

.PHONY : MrPostOGet/TLSHandler.s

# target to generate assembly for a file
MrPostOGet/TLSHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicChatCmake.dir/build.make CMakeFiles/BasicChatCmake.dir/MrPostOGet/TLSHandler.cpp.s
.PHONY : MrPostOGet/TLSHandler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BasicChatCmake"
	@echo "... BasiChatCmake.o"
	@echo "... BasiChatCmake.i"
	@echo "... BasiChatCmake.s"
	@echo "... BasicChat/BasicChatMain.o"
	@echo "... BasicChat/BasicChatMain.i"
	@echo "... BasicChat/BasicChatMain.s"
	@echo "... MBErrorHandling.o"
	@echo "... MBErrorHandling.i"
	@echo "... MBErrorHandling.s"
	@echo "... MrBoboChatt/MBCProtocols.o"
	@echo "... MrBoboChatt/MBCProtocols.i"
	@echo "... MrBoboChatt/MBCProtocols.s"
	@echo "... MrBoboChatt/MBChatConnection.o"
	@echo "... MrBoboChatt/MBChatConnection.i"
	@echo "... MrBoboChatt/MBChatConnection.s"
	@echo "... MrBoboChatt/MrBoboChatt.o"
	@echo "... MrBoboChatt/MrBoboChatt.i"
	@echo "... MrBoboChatt/MrBoboChatt.s"
	@echo "... MrPostOGet/TLSHandler.o"
	@echo "... MrPostOGet/TLSHandler.i"
	@echo "... MrPostOGet/TLSHandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

